// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class AttackInfo;
struct AttackInfoDefaultTypeInternal;
extern AttackInfoDefaultTypeInternal _AttackInfo_default_instance_;
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
class PosInfo;
struct PosInfoDefaultTypeInternal;
extern PosInfoDefaultTypeInternal _PosInfo_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::AttackInfo* Arena::CreateMaybeMessage<::Protocol::AttackInfo>(Arena*);
template<> ::Protocol::ObjectInfo* Arena::CreateMaybeMessage<::Protocol::ObjectInfo>(Arena*);
template<> ::Protocol::PosInfo* Arena::CreateMaybeMessage<::Protocol::PosInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class PosInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PosInfo) */ {
 public:
  inline PosInfo() : PosInfo(nullptr) {}
  ~PosInfo() override;
  explicit PROTOBUF_CONSTEXPR PosInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PosInfo(const PosInfo& from);
  PosInfo(PosInfo&& from) noexcept
    : PosInfo() {
    *this = ::std::move(from);
  }

  inline PosInfo& operator=(const PosInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PosInfo& operator=(PosInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PosInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PosInfo* internal_default_instance() {
    return reinterpret_cast<const PosInfo*>(
               &_PosInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PosInfo& a, PosInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PosInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PosInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PosInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PosInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PosInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PosInfo& from) {
    PosInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PosInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PosInfo";
  }
  protected:
  explicit PosInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectIdFieldNumber = 1,
    kMoveStateFieldNumber = 2,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kZFieldNumber = 5,
    kYawFieldNumber = 6,
    kPitchFieldNumber = 7,
    kRollFieldNumber = 8,
    kDXFieldNumber = 9,
    kDYFieldNumber = 10,
    kDZFieldNumber = 11,
  };
  // uint64 object_id = 1;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // .Protocol.MoveState move_state = 2;
  void clear_move_state();
  ::Protocol::MoveState move_state() const;
  void set_move_state(::Protocol::MoveState value);
  private:
  ::Protocol::MoveState _internal_move_state() const;
  void _internal_set_move_state(::Protocol::MoveState value);
  public:

  // float x = 3;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 4;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 5;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float yaw = 6;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // float pitch = 7;
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // float roll = 8;
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // float d_x = 9;
  void clear_d_x();
  float d_x() const;
  void set_d_x(float value);
  private:
  float _internal_d_x() const;
  void _internal_set_d_x(float value);
  public:

  // float d_y = 10;
  void clear_d_y();
  float d_y() const;
  void set_d_y(float value);
  private:
  float _internal_d_y() const;
  void _internal_set_d_y(float value);
  public:

  // float d_z = 11;
  void clear_d_z();
  float d_z() const;
  void set_d_z(float value);
  private:
  float _internal_d_z() const;
  void _internal_set_d_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PosInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t object_id_;
    int move_state_;
    float x_;
    float y_;
    float z_;
    float yaw_;
    float pitch_;
    float roll_;
    float d_x_;
    float d_y_;
    float d_z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ObjectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() override;
  explicit PROTOBUF_CONSTEXPR ObjectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectInfo(const ObjectInfo& from);
  ObjectInfo(ObjectInfo&& from) noexcept
    : ObjectInfo() {
    *this = ::std::move(from);
  }

  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
               &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ObjectInfo& a, ObjectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObjectInfo& from) {
    ObjectInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ObjectInfo";
  }
  protected:
  explicit ObjectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosInfoFieldNumber = 4,
    kObjectIdFieldNumber = 1,
    kObjectTypeFieldNumber = 2,
    kPlayerTypeFieldNumber = 3,
  };
  // .Protocol.PosInfo pos_Info = 4;
  bool has_pos_info() const;
  private:
  bool _internal_has_pos_info() const;
  public:
  void clear_pos_info();
  const ::Protocol::PosInfo& pos_info() const;
  PROTOBUF_NODISCARD ::Protocol::PosInfo* release_pos_info();
  ::Protocol::PosInfo* mutable_pos_info();
  void set_allocated_pos_info(::Protocol::PosInfo* pos_info);
  private:
  const ::Protocol::PosInfo& _internal_pos_info() const;
  ::Protocol::PosInfo* _internal_mutable_pos_info();
  public:
  void unsafe_arena_set_allocated_pos_info(
      ::Protocol::PosInfo* pos_info);
  ::Protocol::PosInfo* unsafe_arena_release_pos_info();

  // uint64 object_id = 1;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // .Protocol.ObjectType object_type = 2;
  void clear_object_type();
  ::Protocol::ObjectType object_type() const;
  void set_object_type(::Protocol::ObjectType value);
  private:
  ::Protocol::ObjectType _internal_object_type() const;
  void _internal_set_object_type(::Protocol::ObjectType value);
  public:

  // .Protocol.PlayerType player_type = 3;
  void clear_player_type();
  ::Protocol::PlayerType player_type() const;
  void set_player_type(::Protocol::PlayerType value);
  private:
  ::Protocol::PlayerType _internal_player_type() const;
  void _internal_set_player_type(::Protocol::PlayerType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ObjectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::PosInfo* pos_info_;
    uint64_t object_id_;
    int object_type_;
    int player_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class AttackInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AttackInfo) */ {
 public:
  inline AttackInfo() : AttackInfo(nullptr) {}
  ~AttackInfo() override;
  explicit PROTOBUF_CONSTEXPR AttackInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AttackInfo(const AttackInfo& from);
  AttackInfo(AttackInfo&& from) noexcept
    : AttackInfo() {
    *this = ::std::move(from);
  }

  inline AttackInfo& operator=(const AttackInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline AttackInfo& operator=(AttackInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AttackInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const AttackInfo* internal_default_instance() {
    return reinterpret_cast<const AttackInfo*>(
               &_AttackInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AttackInfo& a, AttackInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(AttackInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AttackInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AttackInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AttackInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AttackInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AttackInfo& from) {
    AttackInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AttackInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AttackInfo";
  }
  protected:
  explicit AttackInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectIdFieldNumber = 1,
    kAttackTypeFieldNumber = 2,
    kFinalcamlocXFieldNumber = 3,
    kFinalcamlocYFieldNumber = 4,
    kFinalcamlocZFieldNumber = 5,
    kCamrotPitchFieldNumber = 6,
    kCamrotYawFieldNumber = 7,
    kCamrotRollFieldNumber = 8,
  };
  // uint64 object_id = 1;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // .Protocol.AttackType attack_type = 2;
  void clear_attack_type();
  ::Protocol::AttackType attack_type() const;
  void set_attack_type(::Protocol::AttackType value);
  private:
  ::Protocol::AttackType _internal_attack_type() const;
  void _internal_set_attack_type(::Protocol::AttackType value);
  public:

  // float finalcamloc_x = 3;
  void clear_finalcamloc_x();
  float finalcamloc_x() const;
  void set_finalcamloc_x(float value);
  private:
  float _internal_finalcamloc_x() const;
  void _internal_set_finalcamloc_x(float value);
  public:

  // float finalcamloc_y = 4;
  void clear_finalcamloc_y();
  float finalcamloc_y() const;
  void set_finalcamloc_y(float value);
  private:
  float _internal_finalcamloc_y() const;
  void _internal_set_finalcamloc_y(float value);
  public:

  // float finalcamloc_z = 5;
  void clear_finalcamloc_z();
  float finalcamloc_z() const;
  void set_finalcamloc_z(float value);
  private:
  float _internal_finalcamloc_z() const;
  void _internal_set_finalcamloc_z(float value);
  public:

  // float camrot_pitch = 6;
  void clear_camrot_pitch();
  float camrot_pitch() const;
  void set_camrot_pitch(float value);
  private:
  float _internal_camrot_pitch() const;
  void _internal_set_camrot_pitch(float value);
  public:

  // float camrot_yaw = 7;
  void clear_camrot_yaw();
  float camrot_yaw() const;
  void set_camrot_yaw(float value);
  private:
  float _internal_camrot_yaw() const;
  void _internal_set_camrot_yaw(float value);
  public:

  // float camrot_roll = 8;
  void clear_camrot_roll();
  float camrot_roll() const;
  void set_camrot_roll(float value);
  private:
  float _internal_camrot_roll() const;
  void _internal_set_camrot_roll(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AttackInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t object_id_;
    int attack_type_;
    float finalcamloc_x_;
    float finalcamloc_y_;
    float finalcamloc_z_;
    float camrot_pitch_;
    float camrot_yaw_;
    float camrot_roll_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PosInfo

// uint64 object_id = 1;
inline void PosInfo::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t PosInfo::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t PosInfo::object_id() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.object_id)
  return _internal_object_id();
}
inline void PosInfo::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void PosInfo::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.object_id)
}

// .Protocol.MoveState move_state = 2;
inline void PosInfo::clear_move_state() {
  _impl_.move_state_ = 0;
}
inline ::Protocol::MoveState PosInfo::_internal_move_state() const {
  return static_cast< ::Protocol::MoveState >(_impl_.move_state_);
}
inline ::Protocol::MoveState PosInfo::move_state() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.move_state)
  return _internal_move_state();
}
inline void PosInfo::_internal_set_move_state(::Protocol::MoveState value) {
  
  _impl_.move_state_ = value;
}
inline void PosInfo::set_move_state(::Protocol::MoveState value) {
  _internal_set_move_state(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.move_state)
}

// float x = 3;
inline void PosInfo::clear_x() {
  _impl_.x_ = 0;
}
inline float PosInfo::_internal_x() const {
  return _impl_.x_;
}
inline float PosInfo::x() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.x)
  return _internal_x();
}
inline void PosInfo::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void PosInfo::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.x)
}

// float y = 4;
inline void PosInfo::clear_y() {
  _impl_.y_ = 0;
}
inline float PosInfo::_internal_y() const {
  return _impl_.y_;
}
inline float PosInfo::y() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.y)
  return _internal_y();
}
inline void PosInfo::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void PosInfo::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.y)
}

// float z = 5;
inline void PosInfo::clear_z() {
  _impl_.z_ = 0;
}
inline float PosInfo::_internal_z() const {
  return _impl_.z_;
}
inline float PosInfo::z() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.z)
  return _internal_z();
}
inline void PosInfo::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void PosInfo::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.z)
}

// float yaw = 6;
inline void PosInfo::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float PosInfo::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float PosInfo::yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.yaw)
  return _internal_yaw();
}
inline void PosInfo::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void PosInfo::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.yaw)
}

// float pitch = 7;
inline void PosInfo::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline float PosInfo::_internal_pitch() const {
  return _impl_.pitch_;
}
inline float PosInfo::pitch() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.pitch)
  return _internal_pitch();
}
inline void PosInfo::_internal_set_pitch(float value) {
  
  _impl_.pitch_ = value;
}
inline void PosInfo::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.pitch)
}

// float roll = 8;
inline void PosInfo::clear_roll() {
  _impl_.roll_ = 0;
}
inline float PosInfo::_internal_roll() const {
  return _impl_.roll_;
}
inline float PosInfo::roll() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.roll)
  return _internal_roll();
}
inline void PosInfo::_internal_set_roll(float value) {
  
  _impl_.roll_ = value;
}
inline void PosInfo::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.roll)
}

// float d_x = 9;
inline void PosInfo::clear_d_x() {
  _impl_.d_x_ = 0;
}
inline float PosInfo::_internal_d_x() const {
  return _impl_.d_x_;
}
inline float PosInfo::d_x() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.d_x)
  return _internal_d_x();
}
inline void PosInfo::_internal_set_d_x(float value) {
  
  _impl_.d_x_ = value;
}
inline void PosInfo::set_d_x(float value) {
  _internal_set_d_x(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.d_x)
}

// float d_y = 10;
inline void PosInfo::clear_d_y() {
  _impl_.d_y_ = 0;
}
inline float PosInfo::_internal_d_y() const {
  return _impl_.d_y_;
}
inline float PosInfo::d_y() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.d_y)
  return _internal_d_y();
}
inline void PosInfo::_internal_set_d_y(float value) {
  
  _impl_.d_y_ = value;
}
inline void PosInfo::set_d_y(float value) {
  _internal_set_d_y(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.d_y)
}

// float d_z = 11;
inline void PosInfo::clear_d_z() {
  _impl_.d_z_ = 0;
}
inline float PosInfo::_internal_d_z() const {
  return _impl_.d_z_;
}
inline float PosInfo::d_z() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.d_z)
  return _internal_d_z();
}
inline void PosInfo::_internal_set_d_z(float value) {
  
  _impl_.d_z_ = value;
}
inline void PosInfo::set_d_z(float value) {
  _internal_set_d_z(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.d_z)
}

// -------------------------------------------------------------------

// ObjectInfo

// uint64 object_id = 1;
inline void ObjectInfo::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t ObjectInfo::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t ObjectInfo::object_id() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.object_id)
  return _internal_object_id();
}
inline void ObjectInfo::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void ObjectInfo::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.object_id)
}

// .Protocol.ObjectType object_type = 2;
inline void ObjectInfo::clear_object_type() {
  _impl_.object_type_ = 0;
}
inline ::Protocol::ObjectType ObjectInfo::_internal_object_type() const {
  return static_cast< ::Protocol::ObjectType >(_impl_.object_type_);
}
inline ::Protocol::ObjectType ObjectInfo::object_type() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.object_type)
  return _internal_object_type();
}
inline void ObjectInfo::_internal_set_object_type(::Protocol::ObjectType value) {
  
  _impl_.object_type_ = value;
}
inline void ObjectInfo::set_object_type(::Protocol::ObjectType value) {
  _internal_set_object_type(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.object_type)
}

// .Protocol.PlayerType player_type = 3;
inline void ObjectInfo::clear_player_type() {
  _impl_.player_type_ = 0;
}
inline ::Protocol::PlayerType ObjectInfo::_internal_player_type() const {
  return static_cast< ::Protocol::PlayerType >(_impl_.player_type_);
}
inline ::Protocol::PlayerType ObjectInfo::player_type() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.player_type)
  return _internal_player_type();
}
inline void ObjectInfo::_internal_set_player_type(::Protocol::PlayerType value) {
  
  _impl_.player_type_ = value;
}
inline void ObjectInfo::set_player_type(::Protocol::PlayerType value) {
  _internal_set_player_type(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.player_type)
}

// .Protocol.PosInfo pos_Info = 4;
inline bool ObjectInfo::_internal_has_pos_info() const {
  return this != internal_default_instance() && _impl_.pos_info_ != nullptr;
}
inline bool ObjectInfo::has_pos_info() const {
  return _internal_has_pos_info();
}
inline void ObjectInfo::clear_pos_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.pos_info_ != nullptr) {
    delete _impl_.pos_info_;
  }
  _impl_.pos_info_ = nullptr;
}
inline const ::Protocol::PosInfo& ObjectInfo::_internal_pos_info() const {
  const ::Protocol::PosInfo* p = _impl_.pos_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PosInfo&>(
      ::Protocol::_PosInfo_default_instance_);
}
inline const ::Protocol::PosInfo& ObjectInfo::pos_info() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.pos_Info)
  return _internal_pos_info();
}
inline void ObjectInfo::unsafe_arena_set_allocated_pos_info(
    ::Protocol::PosInfo* pos_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_info_);
  }
  _impl_.pos_info_ = pos_info;
  if (pos_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ObjectInfo.pos_Info)
}
inline ::Protocol::PosInfo* ObjectInfo::release_pos_info() {
  
  ::Protocol::PosInfo* temp = _impl_.pos_info_;
  _impl_.pos_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PosInfo* ObjectInfo::unsafe_arena_release_pos_info() {
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.pos_Info)
  
  ::Protocol::PosInfo* temp = _impl_.pos_info_;
  _impl_.pos_info_ = nullptr;
  return temp;
}
inline ::Protocol::PosInfo* ObjectInfo::_internal_mutable_pos_info() {
  
  if (_impl_.pos_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PosInfo>(GetArenaForAllocation());
    _impl_.pos_info_ = p;
  }
  return _impl_.pos_info_;
}
inline ::Protocol::PosInfo* ObjectInfo::mutable_pos_info() {
  ::Protocol::PosInfo* _msg = _internal_mutable_pos_info();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.pos_Info)
  return _msg;
}
inline void ObjectInfo::set_allocated_pos_info(::Protocol::PosInfo* pos_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pos_info_;
  }
  if (pos_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos_info);
    if (message_arena != submessage_arena) {
      pos_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_info_ = pos_info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.pos_Info)
}

// -------------------------------------------------------------------

// AttackInfo

// uint64 object_id = 1;
inline void AttackInfo::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t AttackInfo::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t AttackInfo::object_id() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.object_id)
  return _internal_object_id();
}
inline void AttackInfo::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void AttackInfo::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.object_id)
}

// .Protocol.AttackType attack_type = 2;
inline void AttackInfo::clear_attack_type() {
  _impl_.attack_type_ = 0;
}
inline ::Protocol::AttackType AttackInfo::_internal_attack_type() const {
  return static_cast< ::Protocol::AttackType >(_impl_.attack_type_);
}
inline ::Protocol::AttackType AttackInfo::attack_type() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.attack_type)
  return _internal_attack_type();
}
inline void AttackInfo::_internal_set_attack_type(::Protocol::AttackType value) {
  
  _impl_.attack_type_ = value;
}
inline void AttackInfo::set_attack_type(::Protocol::AttackType value) {
  _internal_set_attack_type(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.attack_type)
}

// float finalcamloc_x = 3;
inline void AttackInfo::clear_finalcamloc_x() {
  _impl_.finalcamloc_x_ = 0;
}
inline float AttackInfo::_internal_finalcamloc_x() const {
  return _impl_.finalcamloc_x_;
}
inline float AttackInfo::finalcamloc_x() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.finalcamloc_x)
  return _internal_finalcamloc_x();
}
inline void AttackInfo::_internal_set_finalcamloc_x(float value) {
  
  _impl_.finalcamloc_x_ = value;
}
inline void AttackInfo::set_finalcamloc_x(float value) {
  _internal_set_finalcamloc_x(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.finalcamloc_x)
}

// float finalcamloc_y = 4;
inline void AttackInfo::clear_finalcamloc_y() {
  _impl_.finalcamloc_y_ = 0;
}
inline float AttackInfo::_internal_finalcamloc_y() const {
  return _impl_.finalcamloc_y_;
}
inline float AttackInfo::finalcamloc_y() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.finalcamloc_y)
  return _internal_finalcamloc_y();
}
inline void AttackInfo::_internal_set_finalcamloc_y(float value) {
  
  _impl_.finalcamloc_y_ = value;
}
inline void AttackInfo::set_finalcamloc_y(float value) {
  _internal_set_finalcamloc_y(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.finalcamloc_y)
}

// float finalcamloc_z = 5;
inline void AttackInfo::clear_finalcamloc_z() {
  _impl_.finalcamloc_z_ = 0;
}
inline float AttackInfo::_internal_finalcamloc_z() const {
  return _impl_.finalcamloc_z_;
}
inline float AttackInfo::finalcamloc_z() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.finalcamloc_z)
  return _internal_finalcamloc_z();
}
inline void AttackInfo::_internal_set_finalcamloc_z(float value) {
  
  _impl_.finalcamloc_z_ = value;
}
inline void AttackInfo::set_finalcamloc_z(float value) {
  _internal_set_finalcamloc_z(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.finalcamloc_z)
}

// float camrot_pitch = 6;
inline void AttackInfo::clear_camrot_pitch() {
  _impl_.camrot_pitch_ = 0;
}
inline float AttackInfo::_internal_camrot_pitch() const {
  return _impl_.camrot_pitch_;
}
inline float AttackInfo::camrot_pitch() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.camrot_pitch)
  return _internal_camrot_pitch();
}
inline void AttackInfo::_internal_set_camrot_pitch(float value) {
  
  _impl_.camrot_pitch_ = value;
}
inline void AttackInfo::set_camrot_pitch(float value) {
  _internal_set_camrot_pitch(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.camrot_pitch)
}

// float camrot_yaw = 7;
inline void AttackInfo::clear_camrot_yaw() {
  _impl_.camrot_yaw_ = 0;
}
inline float AttackInfo::_internal_camrot_yaw() const {
  return _impl_.camrot_yaw_;
}
inline float AttackInfo::camrot_yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.camrot_yaw)
  return _internal_camrot_yaw();
}
inline void AttackInfo::_internal_set_camrot_yaw(float value) {
  
  _impl_.camrot_yaw_ = value;
}
inline void AttackInfo::set_camrot_yaw(float value) {
  _internal_set_camrot_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.camrot_yaw)
}

// float camrot_roll = 8;
inline void AttackInfo::clear_camrot_roll() {
  _impl_.camrot_roll_ = 0;
}
inline float AttackInfo::_internal_camrot_roll() const {
  return _impl_.camrot_roll_;
}
inline float AttackInfo::camrot_roll() const {
  // @@protoc_insertion_point(field_get:Protocol.AttackInfo.camrot_roll)
  return _internal_camrot_roll();
}
inline void AttackInfo::_internal_set_camrot_roll(float value) {
  
  _impl_.camrot_roll_ = value;
}
inline void AttackInfo::set_camrot_roll(float value) {
  _internal_set_camrot_roll(value);
  // @@protoc_insertion_point(field_set:Protocol.AttackInfo.camrot_roll)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
